name: Pre-Release

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  packages: write

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load version from version.txt
        id: versioning
        run: |
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          BASE=$(echo "$VERSION" | sed -E 's/-pre[0-9]+$//')
          CURRENT_PRE=$(echo "$VERSION" | sed -E 's/^.*-pre([0-9]+)$/\1/')
          NEXT_PRE=$((CURRENT_PRE + 1))
          NEXT_VERSION="${BASE}-pre${NEXT_PRE}"

          echo "base_version=$BASE" >> $GITHUB_ENV
          echo "next_pre_version=$NEXT_VERSION" >> $GITHUB_ENV

          MAJOR=$(echo "$BASE" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$BASE" | cut -d. -f2)
          PATCH=$(echo "$BASE" | cut -d. -f3)
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          prerelease: true
          generate_release_notes: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            MODEL_SERVICE_VERSION=${{ env.version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.version }}
            ghcr.io/${{ github.repository }}:prelatest

      - name: Bump version.txt and tag next pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"

          NEXT_VERSION="${{ env.next_pre_version }}"
          echo "$NEXT_VERSION" > version.txt

          git add version.txt
          git commit -m "chore: bump to $NEXT_VERSION"
          git push origin $CURRENT_BRANCH

          git tag "$NEXT_VERSION"
          git push origin "$NEXT_VERSION"
