name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine release version
        id: versioning
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "Triggered by tag: $VERSION"
          else
            echo "Triggered by push to main"
            VERSION_PRE=$(cat version.txt)
            echo "Previous pre-release version: $VERSION_PRE"
            BASE_VERSION=$(echo "$VERSION_PRE" | sed -E 's/-pre[0-9]+$//')
            MAJ=$(echo "$BASE_VERSION" | cut -d. -f1 | sed 's/v//')
            MIN=$(echo "$BASE_VERSION" | cut -d. -f2)
            PATCH=$(echo "$BASE_VERSION" | cut -d. -f3)
            NEXT_PATCH=$((PATCH + 1))
            VERSION="v${MAJ}.${MIN}.${NEXT_PATCH}"
            echo "Computed release version: $VERSION"
          fi

          echo "version=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          generate_release_notes: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            MODEL_SERVICE_VERSION=${{ env.version }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.version }}

      - name: Bump version.txt and tag next pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          PRE_VERSION="${{ env.version }}-pre1"
          echo "$PRE_VERSION" > version.txt
          git checkout main
          git add version.txt
          git commit -m "chore: bump to $PRE_VERSION"
          git push origin main

          git tag "$PRE_VERSION"
          git push origin "$PRE_VERSION"
